### ISSUE TITLE
[Feature Request]Some Wonderful Traits

### ISSUE THREAD

**Issue by rainsillwood** [phantamanta44/tinkers-evolution#44]
1.Botania-Terrasteel armor can generate mana by 1/tick when equipped all 4 armors.
2.Thaumcraft-Some armors grant a discount to all vis costs
3.EnderIO-Can TiC tools and armors use dark steel anvil to add upgrade?

**Comment by phantamanta44** [comment]
1. dreamwood already has "aura-infused", so you'll want to add a dreamwood part to your armour plate if you want passive mana generation (also, 1/tick would be pretty overpowered)
2. enchanted fabric armour might be a good idea
3. it's on the to-do list, but i dunno if i'll actually go through with it since it sort of accomplishes the same thing as normal tcon modifiers
