### ISSUE TITLE
[1.12.2] keep crashing everytime I take a tick of damage

### ISSUE THREAD

**Issue by atria2468** [phantamanta44/tinkers-evolution#76]
[crash-2021-01-15_11.44.43-server.txt](https://github.com/phantamanta44/tinkers-evolution/files/5822778/crash-2021-01-15_11.44.43-server.txt)

This is on ftb revelation 3.3

**Comment by dualdragoon** [comment]
A group of friends and I are building a pack with this mod and are having the same issue. It seems to be an issue with an API call for Draconic Evolution referring to a non existant class. Likely the API was changed at some point and the call should be updated. Specifically a call to `com/brandon3055/draconicevolution/capabilities/ShieldStateProvider`. Edit: After personally checking the location of the API call and the API itself I'm not really sure why it would be causing an issue because everything *seems* to be right where it should be so maybe the mod author might know more about it.

**Comment by phantamanta44** [comment]
it seems like the version of draconic evolution you're using here is very out-of-date (even when this issue was created); the api update actually happened *after* the version you have in this modpack
