### ISSUE TITLE
error craftweaker again on E2Expert

### ISSUE THREAD

**Issue by jimmy06200** [phantamanta44/tinkers-evolution#9]
ERROR miscRecepies.zs 351 could not resolve plustic invarnugget
ERROR  executing 
ERROR  miscRecepies.zs 97 could not resolve plustic invarnblock
ERROR cannot remove recepies for a null item
ERROR while applying action

Thx to you and your update

**Comment by phantamanta44** [comment]
this is plustic's problem; it only registers invar items if no other mod adds a tinkers' construct invar material. since tconevo registers an invar material, plustic decides not to register invar items. [relevant code is here](https://github.com/Landmaster/PlusTiC/blob/38436d73461bc77ad643a2eb926cc8863e5bb534/src/main/java/landmaster/plustic/modules/ModuleBase.java#L102)

one possibility is for you to disable tconevo invar, which should allow plustic to register its invar stuff. i'm not really sure why the e2:e authors didn't just use thermal foundation invar for their recipe tweaking...

**Comment by jimmy06200** [comment]
Sorry for the wait i way to busy by my work at the moment but how can i find the line for disable your tconevo invar ? 
Thx again =p

**Comment by phantamanta44** [comment]
add the entry "invar" to the "disabledMaterials" list in the config

**Comment by jimmy06200** [comment]
thx
